return {
  [463856573512] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856573646] = {
            [1] = {
              ["id"] = 4519,
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "乔小傻瓜",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856573646.0,
              ["time"] = 1530167073.0,
              ["MailId"] = 4519,
            },
          },
          [463856573607] = {
            [1] = {
              ["id"] = 4503,
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "旋律小易",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856573607.0,
              ["time"] = 1530092293.0,
              ["MailId"] = 4503,
            },
          },
        },
      },
    },
  },
  [463856574259] = {
    ["ChatData"] = {
      ["data"] = {
        [6] = {
          [463856574260] = {
            [1] = {
              ["status"] = 2,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我在<color=#FEC542>副本星星</color>的排名超过你了，加油吧！",
              ["fromname"] = "优雅樱花",
              ["channel"] = 6,
              ["fromid"] = 463856574260.0,
              ["source"] = 0,
              ["time"] = 1532957052.0,
            },
          },
        },
      },
    },
  },
  [481036437171] = {
    ["ChatData"] = {
      ["data"] = {
        [6] = {
          [481036437168] = {
            [1] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我在<color=#FEC542>水银等级</color>的排名超过你了，加油吧！",
              ["fromname"] = "潇洒林赛",
              ["channel"] = 6,
              ["fromid"] = 481036437168.0,
              ["source"] = 0,
              ["time"] = 1532767635.0,
            },
            [2] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 2,
              ["message"] = "我在<color=#FEC542>水银等级</color>的排名超过你了，加油吧！",
              ["fromname"] = "潇洒林赛",
              ["channel"] = 6,
              ["fromid"] = 481036437168.0,
              ["source"] = 0,
              ["time"] = 1532757776.0,
            },
            [3] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 3,
              ["message"] = "我在<color=#FEC542>水银等级</color>的排名超过你了，加油吧！",
              ["fromname"] = "潇洒林赛",
              ["channel"] = 6,
              ["fromid"] = 481036437168.0,
              ["source"] = 0,
              ["time"] = 1532757844.0,
            },
          },
          [481036437169] = {
            [1] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532758622.0,
            },
            [2] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 2,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532758622.0,
            },
            [3] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 3,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532758659.0,
            },
            [4] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 4,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532758659.0,
            },
            [5] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 5,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532758706.0,
            },
            [6] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 6,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532758706.0,
            },
            [7] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 7,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759058.0,
            },
            [8] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 8,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759058.0,
            },
            [9] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 9,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532762703.0,
            },
            [10] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 10,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759192.0,
            },
            [11] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 11,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759192.0,
            },
            [12] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 12,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759226.0,
            },
            [13] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 13,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759226.0,
            },
            [14] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 14,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532762624.0,
            },
            [15] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 15,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759248.0,
            },
            [16] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 16,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759347.0,
            },
            [17] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 17,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759347.0,
            },
            [18] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 18,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759380.0,
            },
            [19] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 19,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759381.0,
            },
            [20] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 20,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759401.0,
            },
            [21] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 21,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759401.0,
            },
            [22] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 22,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761348.0,
            },
            [23] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 23,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759512.0,
            },
            [24] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 24,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759512.0,
            },
            [25] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 25,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761133.0,
            },
            [26] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 26,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759520.0,
            },
            [27] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 27,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759520.0,
            },
            [28] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 28,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761094.0,
            },
            [29] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 29,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759653.0,
            },
            [30] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 30,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759653.0,
            },
            [31] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 31,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761094.0,
            },
            [32] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 32,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760826.0,
            },
            [33] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 33,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760826.0,
            },
            [34] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 34,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760803.0,
            },
            [35] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 35,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760803.0,
            },
            [36] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 36,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760787.0,
            },
            [37] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 37,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760787.0,
            },
            [38] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 38,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760718.0,
            },
            [39] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 39,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760718.0,
            },
            [40] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 40,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760681.0,
            },
            [41] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 41,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760681.0,
            },
            [42] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 42,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760614.0,
            },
            [43] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 43,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760614.0,
            },
            [44] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 44,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760574.0,
            },
            [45] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 45,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760573.0,
            },
            [46] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 46,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760538.0,
            },
            [47] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 47,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760538.0,
            },
            [48] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 48,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760501.0,
            },
            [49] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 49,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760501.0,
            },
            [50] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 50,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532763001.0,
            },
            [51] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 51,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760446.0,
            },
            [52] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 52,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760446.0,
            },
            [53] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 53,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532763001.0,
            },
            [54] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 54,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760400.0,
            },
            [55] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 55,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760400.0,
            },
            [56] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 56,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532762703.0,
            },
            [57] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 57,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532762624.0,
            },
            [58] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 58,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760228.0,
            },
            [59] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 59,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760228.0,
            },
            [60] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 60,
              ["message"] = "我在<color=#FEC542>水银等级</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532762541.0,
            },
            [61] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 61,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760152.0,
            },
            [62] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 62,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532760152.0,
            },
            [63] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 63,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761424.0,
            },
            [64] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 64,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761424.0,
            },
            [65] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 65,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759965.0,
            },
            [66] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 66,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759964.0,
            },
            [67] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 67,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761348.0,
            },
            [68] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 68,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759869.0,
            },
            [69] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 69,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759869.0,
            },
            [70] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 70,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761207.0,
            },
            [71] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 71,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761207.0,
            },
            [72] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 72,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759823.0,
            },
            [73] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 73,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759823.0,
            },
            [74] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 74,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532761133.0,
            },
            [75] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 75,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759746.0,
            },
            [76] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 76,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759746.0,
            },
            [77] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 77,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759248.0,
            },
            [78] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 78,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759692.0,
            },
            [79] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 79,
              ["message"] = "我在<color=#FEC542>竞技财力</color>的排名超过你了，加油吧！",
              ["fromname"] = "好哥哥",
              ["channel"] = 6,
              ["fromid"] = 481036437169.0,
              ["source"] = 0,
              ["time"] = 1532759692.0,
            },
          },
        },
      },
    },
  },
  [463856574260] = {
    ["ChatData"] = {
      ["data"] = {
        [6] = {
          [463856574259] = {
            [1] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我在<color=#FEC542>副本星星</color>的排名超过你了，加油吧！",
              ["fromname"] = "柔情春春",
              ["channel"] = 6,
              ["fromid"] = 463856574259.0,
              ["source"] = 0,
              ["time"] = 1532957199.0,
            },
          },
        },
      },
    },
  },
  [463856573005] = {
    ["ChatData"] = {
      ["data"] = {
        [6] = {
          [117] = {
            [1] = {
              ["status"] = 2,
              ["ChatIdx"] = 1,
              ["idx"] = 1,
              ["message"] = "暂离",
              ["fromname"] = "极乐石祥",
              ["channel"] = 6,
              ["fromid"] = 117,
              ["source"] = 0,
              ["time"] = 1529583514.0,
            },
          },
          [167] = {
            [1] = {
              ["status"] = 2,
              ["ChatIdx"] = 1,
              ["idx"] = 1,
              ["message"] = "6",
              ["fromname"] = "智囊卫萌",
              ["channel"] = 6,
              ["source"] = 0,
              ["fromid"] = 167,
              ["PlayerData"] = {
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["time"] = 1529583945.0,
            },
          },
        },
        [8] = {
          [463856573808] = {
            [1] = {
              ["id"] = 57454,
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "辉煌天宇",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856573808.0,
              ["time"] = 1531882906.0,
              ["MailId"] = 57454,
            },
          },
        },
      },
    },
  },
  [463856572646] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856574260] = {
            [1] = {
              ["id"] = 94279,
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "优雅樱花",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856574260.0,
              ["time"] = 1532956866.0,
              ["MailId"] = 94279,
            },
          },
          [463856574259] = {
            [1] = {
              ["id"] = 94147,
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "柔情春春",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856574259.0,
              ["time"] = 1532951129.0,
              ["MailId"] = 94147,
            },
          },
          [463856573646] = {
            [1] = {
              ["id"] = 4488,
              ["status"] = 2,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "乔小傻瓜",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856573646.0,
              ["time"] = 1530006253.0,
              ["MailId"] = 4488,
            },
          },
          [463856573607] = {
            [1] = {
              ["id"] = 4479,
              ["status"] = 2,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["fromname"] = "旋律小易",
              ["channel"] = 8,
              ["source"] = 0,
              ["fromid"] = 463856573607.0,
              ["time"] = 1529918315.0,
              ["MailId"] = 4479,
            },
          },
        },
        [6] = {
          [463856573685] = {
            [1] = {
              ["status"] = 2,
              ["ChatIdx"] = 1,
              ["idx"] = 1,
              ["message"] = "1111",
              ["fromname"] = "jerry1",
              ["channel"] = 6,
              ["source"] = 0,
              ["fromid"] = 463856573685.0,
              ["PlayerData"] = {
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["time"] = 1530067725.0,
            },
          },
          [1283] = {
            [1] = {
              ["status"] = 2,
              ["ChatIdx"] = 1,
              ["idx"] = 1,
              ["message"] = "6",
              ["fromname"] = "幼麟吉洽",
              ["channel"] = 6,
              ["source"] = 0,
              ["fromid"] = 1283,
              ["PlayerData"] = {
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["time"] = 1530082514.0,
            },
          },
        },
      },
    },
  },
  [463856568047] = {
    ["ChatData"] = {
      ["data"] = {
        [6] = {
          [463856574260] = {
            [1] = {
              ["status"] = 1,
              ["ChatIdx"] = 0,
              ["idx"] = 1,
              ["message"] = "我在<color=#FEC542>圣坛守护</color>的排名超过你了，加油吧！",
              ["fromname"] = "优雅樱花",
              ["channel"] = 6,
              ["fromid"] = 463856574260.0,
              ["time"] = 1533010746.0,
              ["source"] = 0,
            },
          },
        },
      },
    },
  },
}